#### 1. Import pandas library

In [1]:
import pandas as pd

#### 2. Import pymysql and sqlalchemy as you have learnt in the lesson of importing/exporting data

In [3]:
import pymysql
from sqlalchemy import create_engine

#### 3. Create a mysql engine to set the connection to the server. Check the connection details in [this link](https://relational.fit.cvut.cz/search?tableCount%5B%5D=0-10&tableCount%5B%5D=10-30&dataType%5B%5D=Numeric&databaseSize%5B%5D=KB&databaseSize%5B%5D=MB)

In [9]:
engine = create_engine('mysql+pymysql://guest:relational@relational.fit.cvut.cz/stats')

#### 4. Import the users table

In [14]:
users = pd.read_sql_query('SELECT * FROM stats.users', engine)

#### 5. Rename Id column to userId

In [19]:
users = users.rename(index=str, columns={"Id": "userId"})
users.head()

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,1920,-1,NaN,None
1,2,101,2010-07-19 14:01:36,Geoff Dalgas,2013-11-12 22:07:23,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the StackOverflow team. Find ...,25,3,0,2,37.0,None
2,3,101,2010-07-19 15:34:50,Jarrod Dixon,2014-08-08 06:42:58,http://stackoverflow.com,"New York, NY","<p><a href=""http://blog.stackoverflow.com/2009...",22,19,0,3,35.0,None
3,4,101,2010-07-19 19:03:27,Emmett,2014-01-02 09:31:02,http://minesweeperonline.com,"San Francisco, CA",<p>currently at a startup in SF</p>\n\n<p>form...,11,0,0,1998,28.0,http://i.stack.imgur.com/d1oHX.jpg
4,5,6792,2010-07-19 19:03:57,Shane,2014-08-13 00:23:47,http://www.statalgo.com,"New York, NY",<p>Quantitative researcher focusing on statist...,1145,662,5,54503,35.0,None

#### 6. Import the posts table.

In [15]:
posts = pd.read_sql_query('SELECT * FROM stats.posts', engine)

#### 7. Rename Id column to postId and OwnerUserId to userId

In [21]:
posts = posts.rename(index=str, columns={"Id": "postId", "OwnerUserId": "userId"})
posts.head()

,postId,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,userId,LasActivityDate,Title,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,1,1,15.0,2010-07-19 19:12:12,23,1278.0,<p>How should I elicit prior distributions fro...,8.0,2010-09-15 21:08:26,Eliciting priors from experts,...,5.0,1,14.0,NaN,NaT,NaT,NaN,NaT,None,None
1,2,1,59.0,2010-07-19 19:12:57,22,8198.0,<p>In many different statistical methods there...,24.0,2012-11-12 09:21:54,What is normality?,...,7.0,1,8.0,88.0,2010-08-07 17:56:44,NaT,NaN,NaT,None,None
2,3,1,5.0,2010-07-19 19:13:28,54,3613.0,<p>What are some valuable Statistical Analysis...,18.0,2013-05-27 14:48:36,What are some valuable Statistical Analysis op...,...,19.0,4,36.0,183.0,2011-02-12 05:50:03,2010-07-19 19:13:28,NaN,NaT,None,None
3,4,1,135.0,2010-07-19 19:13:31,13,5224.0,<p>I have two groups of data. Each with a dif...,23.0,2010-09-08 03:00:19,Assessing the significance of differences in d...,...,5.0,2,2.0,NaN,NaT,NaT,NaN,NaT,None,None
4,5,2,NaN,2010-07-19 19:14:43,81,NaN,"<p>The R-project</p>\n\n<p><a href=""http://www...",23.0,2010-07-19 19:21:15,None,...,NaN,3,NaN,23.0,2010-07-19 19:21:15,2010-07-19 19:14:43,3.0,NaT,None,None

#### 8. Define new dataframes for users and posts with the following selected columns:
    **users columns**: userId, Reputation,Views,UpVotes,DownVotes
    **posts columns**: postId, Score,userID,ViewCount,CommentCount

In [51]:
users_new = users[['userId', 'Reputation', 'Views', 'UpVotes', 'DownVotes']].copy()
posts_new = posts[['postId', 'Score', 'userId', 'ViewCount', 'CommentCount']].copy()
users_new.head()
posts_new.head()

   userId  Reputation  Views  UpVotes  DownVotes
0      -1           1      0     5007       1920
1       2         101     25        3          0
2       3         101     22       19          0
3       4         101     11        0          0
4       5        6792   1145      662          5

#### 8. Merge both dataframes, users and posts. 
You will need to make a [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) of posts and users dataframes.

In [33]:
users_posts = pd.merge(users_new, posts_new, on='userId')
users_posts.head(10)

,userId,Reputation,Views,UpVotes,DownVotes,postId,Score,ViewCount,CommentCount
0,-1,1,0,5007,1920,2175,0,NaN,0
1,-1,1,0,5007,1920,8576,0,NaN,0
2,-1,1,0,5007,1920,8578,0,NaN,0
3,-1,1,0,5007,1920,8981,0,NaN,0
4,-1,1,0,5007,1920,8982,0,NaN,0
5,-1,1,0,5007,1920,9857,0,NaN,0
6,-1,1,0,5007,1920,9858,0,NaN,0
7,-1,1,0,5007,1920,9860,0,NaN,0
8,-1,1,0,5007,1920,10130,0,NaN,0
9,-1,1,0,5007,1920,10131,0,NaN,0

#### 9. How many missing values do you have in your merged dataframe? On which columns?

In [30]:
null_cols = users_posts.isnull().sum()
null_cols[null_cols > 0]

ViewCount    48396
dtype: int64

#### 10. You will need to make something with missing values.  Will you clean or filling them? Explain. 
**Remember** to check the results of your code before passing to the next step

In [41]:
users_posts[['ViewCount']] = users_posts[['ViewCount']].fillna(0)
print(set(users_posts['ViewCount']))

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 8198.0, 7.0, 8.0, 9.0, 6.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 116.0, 117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 124.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 139.0, 140.0, 141.0, 142.0, 143.0, 144.0, 145.0, 146.0, 147.0, 148.0, 149.0, 150.0, 151.0, 152.0, 8341.0, 154.0, 155.0, 156.0, 157.0, 158.0, 159.0, 160.0, 161.0, 24738.0, 162.0, 164.0, 165.0, 166.0, 167.0, 168.0, 169.0, 170.0, 171.0, 172.0, 173.0, 174.0, 8366.0, 176.0, 177.0, 178.0, 175.0, 180.0, 181.0, 182.0, 183.0, 184.0, 179.0, 185.0, 187.0, 188.0, 189.0, 190.0, 191.0, 192.0, 193.0, 194.0, 195.0, 196.0, 197.0, 8386.0, 198.0, 200.0, 201.0, 202.0, 203.0, 199.0, 205.0, 206.0, 204.0, 208.0, 209.0, 210.0, 207.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 8410.0, 219.0, 220.0, 221.0, 218.0, 223.0, 224.0, 225.0, 226.0, 227.0, 228.0, 222.0, 230.0, 231.0, 232.0, 233.0, 234.0, 235.0, 236.0, 237.0, 238.0, 239.0, 240.0, 241.0, 242.0, 243.0, 244.0, 245.0, 246.0, 247.0, 248.0, 249.0, 250.0, 251.0, 252.0, 253.0, 254.0, 255.0, 256.0, 257.0, 258.0, 259.0, 260.0, 261.0, 262.0, 263.0, 264.0, 265.0, 8456.0, 267.0, 268.0, 269.0, 270.0, 271.0, 272.0, 273.0, 274.0, 275.0, 276.0, 277.0, 278.0, 279.0, 280.0, 281.0, 282.0, 283.0, 284.0, 285.0, 286.0, 287.0, 288.0, 289.0, 290.0, 291.0, 292.0, 293.0, 294.0, 8479.0, 296.0, 297.0, 298.0, 299.0, 300.0, 301.0, 302.0, 303.0, 304.0, 305.0, 306.0, 307.0, 308.0, 309.0, 310.0, 311.0, 312.0, 313.0, 314.0, 315.0, 316.0, 317.0, 318.0, 319.0, 320.0, 321.0, 322.0, 323.0, 324.0, 325.0, 326.0, 327.0, 328.0, 329.0, 330.0, 331.0, 332.0, 333.0, 334.0, 335.0, 336.0, 337.0, 338.0, 339.0, 8532.0, 340.0, 342.0, 343.0, 344.0, 345.0, 346.0, 347.0, 348.0, 349.0, 341.0, 351.0, 350.0, 353.0, 354.0, 355.0, 356.0, 357.0, 358.0, 359.0, 360.0, 361.0, 362.0, 363.0, 364.0, 365.0, 366.0, 367.0, 368.0, 369.0, 370.0, 371.0, 372.0, 373.0, 8559.0, 375.0, 376.0, 377.0, 378.0, 379.0, 380.0, 381.0, 382.0, 383.0, 384.0, 385.0, 386.0, 387.0, 388.0, 389.0, 390.0, 391.0, 392.0, 393.0, 8585.0, 395.0, 394.0, 397.0, 398.0, 396.0, 400.0, 401.0, 402.0, 403.0, 404.0, 405.0, 406.0, 407.0, 408.0, 409.0, 410.0, 411.0, 412.0, 413.0, 414.0, 415.0, 416.0, 417.0, 418.0, 419.0, 420.0, 421.0, 422.0, 423.0, 424.0, 425.0, 426.0, 427.0, 428.0, 429.0, 430.0, 431.0, 432.0, 433.0, 434.0, 435.0, 436.0, 437.0, 438.0, 439.0, 440.0, 441.0, 442.0, 443.0, 444.0, 445.0, 446.0, 447.0, 448.0, 449.0, 8638.0, 451.0, 450.0, 453.0, 454.0, 455.0, 456.0, 457.0, 458.0, 452.0, 460.0, 461.0, 462.0, 463.0, 464.0, 465.0, 466.0, 467.0, 468.0, 469.0, 470.0, 8654.0, 472.0, 473.0, 474.0, 475.0, 476.0, 477.0, 478.0, 8236.0, 480.0, 481.0, 482.0, 483.0, 484.0, 485.0, 486.0, 487.0, 488.0, 489.0, 490.0, 491.0, 492.0, 493.0, 494.0, 25066.0, 496.0, 497.0, 498.0, 499.0, 500.0, 501.0, 502.0, 8688.0, 504.0, 505.0, 506.0, 507.0, 508.0, 8692.0, 510.0, 511.0, 503.0, 513.0, 514.0, 515.0, 516.0, 512.0, 518.0, 519.0, 520.0, 521.0, 522.0, 523.0, 524.0, 525.0, 526.0, 527.0, 528.0, 529.0, 8722.0, 531.0, 532.0, 533.0, 534.0, 535.0, 536.0, 66071.0, 538.0, 537.0, 539.0, 541.0, 542.0, 543.0, 544.0, 545.0, 546.0, 547.0, 548.0, 540.0, 550.0, 551.0, 552.0, 553.0, 554.0, 555.0, 556.0, 557.0, 558.0, 559.0, 560.0, 561.0, 562.0, 563.0, 564.0, 565.0, 566.0, 567.0, 568.0, 569.0, 570.0, 571.0, 572.0, 573.0, 574.0, 575.0, 576.0, 577.0, 578.0, 579.0, 580.0, 581.0, 582.0, 583.0, 584.0, 585.0, 586.0, 587.0, 588.0, 589.0, 590.0, 591.0, 592.0, 593.0, 594.0, 16978.0, 596.0, 597.0, 598.0, 595.0, 600.0, 601.0, 602.0, 603.0, 604.0, 605.0, 606.0, 607.0, 608.0, 609.0, 610.0, 611.0, 612.0, 613.0, 614.0, 615.0, 616.0, 617.0, 618.0, 619.0, 620.0, 25197.0, 622.0, 623.0, 621.0, 625.0, 626.0, 627.0, 628.0, 629.0, 630.0, 631.0, 632.0, 633.0, 8826.0, 635.0, 636.0, 634.0, 638.0, 637.0, 640.0, 639.0, 642.0, 641.0, 644.0, 645.0, 646.0, 647.0, 648.0, 649.0, 650.0, 651.0, 652.0, 653.0, 654.0, 655.0, 656.0, 657.0, 658.0, 659.0, 660.0, 661.0, 662.0, 663.0, 664.0, 665.0, 666.0, 667.0, 668.0, 8861.0, 670.0, 671.0, 672.0, 673.0, 674.0, 675.0, 676.0, 677.0, 17062.0, 679.0, 680.0, 681.0, 682.0, 678.0, 684.0, 685.0, 686.0, 687.0, 688.0, 689.0, 690.0, 691.0, 692.0, 693.0, 694.0, 695.0, 696.0, 697.0, 698.0, 699.0, 700.0, 701.0, 702.0, 703.0, 704.0, 705.0, 706.0, 707.0, 708.0, 709.0, 710.0, 711.0, 712.0, 713.0, 714.0, 715.0, 716.0, 717.0, 718.0, 719.0, 720.0, 8908.0, 722.0, 723.0, 724.0, 725.0, 721.0, 727.0, 728.0, 729.0, 730.0, 731.0, 732.0, 733.0, 726.0, 735.0, 734.0, 737.0, 738.0, 739.0, 740.0, 741.0, 742.0, 743.0, 744.0, 736.0, 746.0, 745.0, 748.0, 749.0, 750.0, 751.0, 752.0, 753.0, 754.0, 755.0, 756.0, 757.0, 758.0, 759.0, 760.0, 761.0, 762.0, 763.0, 764.0, 765.0, 766.0, 767.0, 8960.0, 769.0, 153.0, 771.0, 772.0, 773.0, 774.0, 775.0, 776.0, 777.0, 778.0, 779.0, 780.0, 781.0, 782.0, 783.0, 8974.0, 785.0, 786.0, 787.0, 788.0, 789.0, 790.0, 784.0, 792.0, 793.0, 794.0, 795.0, 49948.0, 797.0, 796.0, 799.0, 800.0, 801.0, 802.0, 798.0, 804.0, 805.0, 806.0, 807.0, 803.0, 8994.0, 810.0, 811.0, 812.0, 813.0, 814.0, 815.0, 816.0, 817.0, 818.0, 819.0, 820.0, 163.0, 821.0, 823.0, 824.0, 825.0, 826.0, 827.0, 9020.0, 829.0, 830.0, 831.0, 832.0, 833.0, 834.0, 835.0, 836.0, 837.0, 838.0, 839.0, 840.0, 841.0, 842.0, 843.0, 844.0, 845.0, 846.0, 847.0, 8309.0, 849.0, 850.0, 851.0, 852.0, 853.0, 854.0, 855.0, 856.0, 857.0, 858.0, 859.0, 860.0, 861.0, 862.0, 863.0, 864.0, 865.0, 866.0, 867.0, 868.0, 869.0, 870.0, 871.0, 872.0, 873.0, 874.0, 875.0, 876.0, 877.0, 17255.0, 879.0, 880.0, 881.0, 878.0, 883.0, 884.0, 885.0, 9075.0, 887.0, 888.0, 889.0, 886.0, 891.0, 892.0, 893.0, 894.0, 895.0, 896.0, 890.0, 898.0, 899.0, 900.0, 901.0, 902.0, 897.0, 904.0, 905.0, 906.0, 907.0, 908.0, 909.0, 9102.0, 910.0, 912.0, 913.0, 914.0, 915.0, 916.0, 911.0, 918.0, 919.0, 920.0, 921.0, 922.0, 923.0, 924.0, 925.0, 926.0, 927.0, 928.0, 929.0, 930.0, 931.0, 932.0, 933.0, 934.0, 935.0, 186.0, 937.0, 938.0, 939.0, 940.0, 936.0, 942.0, 943.0, 944.0, 941.0, 946.0, 947.0, 948.0, 945.0, 950.0, 951.0, 952.0, 953.0, 954.0, 955.0, 956.0, 957.0, 958.0, 959.0, 960.0, 961.0, 962.0, 963.0, 964.0, 965.0, 966.0, 967.0, 968.0, 969.0, 970.0, 971.0, 972.0, 973.0, 974.0, 975.0, 976.0, 977.0, 978.0, 979.0, 980.0, 981.0, 982.0, 983.0, 984.0, 985.0, 986.0, 987.0, 988.0, 989.0, 990.0, 991.0, 992.0, 993.0, 994.0, 995.0, 996.0, 997.0, 998.0, 999.0, 1000.0, 1001.0, 1002.0, 1003.0, 1004.0, 1005.0, 1006.0, 1007.0, 1008.0, 1009.0, 25583.0, 1010.0, 1012.0, 1013.0, 1014.0, 9207.0, 1016.0, 1017.0, 9210.0, 1019.0, 17403.0, 25597.0, 1022.0, 1023.0, 1021.0, 1024.0, 16486.0, 1026.0, 1028.0, 1029.0, 1030.0, 1027.0, 1032.0, 1031.0, 1034.0, 1035.0, 1036.0, 1037.0, 8346.0, 1039.0, 1040.0, 1041.0, 9231.0, 1043.0, 1044.0, 17429.0, 1046.0, 16490.0, 1048.0, 1049.0, 1050.0, 1045.0, 1052.0, 1053.0, 1054.0, 1055.0, 1056.0, 1057.0, 1058.0, 1051.0, 1060.0, 1061.0, 211.0, 1063.0, 1064.0, 1065.0, 1066.0, 1067.0, 1068.0, 1069.0, 1070.0, 1071.0, 1072.0, 1073.0, 1074.0, 1075.0, 1076.0, 1078.0, 9271.0, 1079.0, 1081.0, 1082.0, 1083.0, 1084.0, 1085.0, 1086.0, 1087.0, 1080.0, 1089.0, 1090.0, 1091.0, 1092.0, 1093.0, 1094.0, 1095.0, 1096.0, 1097.0, 1098.0, 1099.0, 1100.0, 1101.0, 1102.0, 1103.0, 1104.0, 1105.0, 1106.0, 1107.0, 1108.0, 1109.0, 1110.0, 1111.0, 1112.0, 1114.0, 1115.0, 1116.0, 1117.0, 1118.0, 1119.0, 1120.0, 1121.0, 1123.0, 1124.0, 1125.0, 1126.0, 1127.0, 1128.0, 1129.0, 1130.0, 1131.0, 1132.0, 1133.0, 1134.0, 1135.0, 1136.0, 1137.0, 1138.0, 1139.0, 1140.0, 1141.0, 1142.0, 1143.0, 1144.0, 1145.0, 1147.0, 1148.0, 1149.0, 17534.0, 1153.0, 229.0, 1155.0, 1156.0, 1157.0, 1158.0, 1159.0, 1160.0, 1161.0, 1162.0, 1163.0, 1164.0, 1165.0, 1166.0, 1167.0, 1168.0, 1169.0, 1170.0, 1171.0, 1172.0, 1173.0, 1174.0, 1175.0, 1176.0, 9369.0, 1178.0, 1177.0, 1180.0, 8375.0, 1181.0, 1183.0, 1182.0, 1185.0, 1186.0, 1179.0, 1188.0, 1189.0, 1190.0, 1191.0, 1192.0, 1193.0, 1194.0, 1195.0, 1196.0, 1197.0, 1198.0, 1199.0, 1200.0, 1201.0, 9390.0, 1203.0, 1204.0, 1205.0, 1206.0, 1207.0, 1208.0, 1209.0, 1210.0, 1211.0, 1213.0, 1214.0, 1215.0, 1216.0, 1217.0, 1218.0, 1219.0, 1220.0, 1221.0, 1223.0, 1224.0, 1225.0, 1226.0, 1227.0, 1228.0, 1229.0, 1230.0, 1231.0, 1232.0, 1233.0, 9426.0, 1234.0, 1236.0, 1237.0, 1235.0, 1239.0, 1240.0, 1241.0, 1242.0, 1243.0, 1244.0, 1245.0, 1246.0, 1249.0, 1250.0, 1251.0, 9444.0, 1252.0, 1254.0, 1255.0, 1256.0, 1257.0, 1258.0, 1259.0, 1260.0, 1261.0, 1253.0, 1263.0, 1264.0, 1265.0, 1266.0, 1267.0, 1268.0, 1269.0, 1270.0, 1271.0, 1273.0, 1274.0, 34044.0, 1276.0, 1278.0, 1279.0, 1277.0, 1280.0, 1282.0, 1283.0, 1284.0, 1285.0, 1286.0, 1287.0, 1288.0, 9481.0, 1290.0, 1291.0, 1289.0, 1293.0, 1294.0, 1295.0, 1296.0, 1297.0, 1298.0, 1299.0, 1300.0, 1301.0, 1302.0, 1303.0, 1304.0, 1305.0, 1306.0, 1307.0, 1308.0, 1309.0, 1310.0, 1311.0, 1312.0, 1313.0, 1314.0, 1315.0, 1316.0, 1317.0, 1318.0, 1319.0, 1320.0, 1321.0, 1322.0, 1323.0, 1325.0, 1326.0, 1327.0, 1328.0, 1329.0, 1330.0, 1331.0, 1332.0, 1333.0, 1334.0, 1335.0, 1336.0, 1337.0, 75058.0, 1339.0, 1340.0, 266.0, 1342.0, 1343.0, 1344.0, 1345.0, 1346.0, 1347.0, 1348.0, 1349.0, 1350.0, 1351.0, 1352.0, 1354.0, 1355.0, 1356.0, 1357.0, 1358.0, 1359.0, 1361.0, 1362.0, 1363.0, 1364.0, 1365.0, 1366.0, 1367.0, 1368.0, 1369.0, 8413.0, 1371.0, 1370.0, 1372.0, 1374.0, 1375.0, 1373.0, 1377.0, 1378.0, 1379.0, 1380.0, 1382.0, 1383.0, 25960.0, 1384.0, 25962.0, 1387.0, 1388.0, 1386.0, 1390.0, 1391.0, 1392.0, 1393.0, 1394.0, 1395.0, 1396.0, 1397.0, 1398.0, 1399.0, 1400.0, 1401.0, 1402.0, 1403.0, 1404.0, 1405.0, 1406.0, 1407.0, 1409.0, 1410.0, 1411.0, 1413.0, 1416.0, 1417.0, 1418.0, 1419.0, 1420.0, 1421.0, 1422.0, 1423.0, 1424.0, 1425.0, 1426.0, 1427.0, 1428.0, 1429.0, 1430.0, 1431.0, 9615.0, 1433.0, 1434.0, 1435.0, 66972.0, 1436.0, 1438.0, 1439.0, 1440.0, 1441.0, 1442.0, 1443.0, 1444.0, 1445.0, 1446.0, 1448.0, 1449.0, 1450.0, 1452.0, 1454.0, 1455.0, 1457.0, 1458.0, 1459.0, 1460.0, 1461.0, 1462.0, 1463.0, 1464.0, 1465.0, 1466.0, 1467.0, 1468.0, 1470.0, 1471.0, 1472.0, 1473.0, 1474.0, 1475.0, 1476.0, 1477.0, 1478.0, 1479.0, 1484.0, 295.0, 1485.0, 1487.0, 1486.0, 1489.0, 1490.0, 16577.0, 1492.0, 1493.0, 8200.0, 1488.0, 1494.0, 1497.0, 1498.0, 1491.0, 1499.0, 1500.0, 1502.0, 1503.0, 1496.0, 1505.0, 1506.0, 1688.0, 1508.0, 1507.0, 1509.0, 1512.0, 1513.0, 1514.0, 1515.0, 1517.0, 1518.0, 1519.0, 1520.0, 1521.0, 1522.0, 1523.0, 1524.0, 1525.0, 1526.0, 1527.0, 1528.0, 1529.0, 1531.0, 1532.0, 1533.0, 1534.0, 1535.0, 1536.0, 1537.0, 16587.0, 1539.0, 1540.0, 1541.0, 1542.0, 1543.0, 1544.0, 1545.0, 1546.0, 1547.0, 1548.0, 9741.0, 1549.0, 1551.0, 1552.0, 1550.0, 1555.0, 1556.0, 1557.0, 9750.0, 1560.0, 1561.0, 1562.0, 1563.0, 1564.0, 1565.0, 1566.0, 1567.0, 1568.0, 8203.0, 1569.0, 1571.0, 1572.0, 1573.0, 1574.0, 1575.0, 1570.0, 1577.0, 1578.0, 1579.0, 9772.0, 1580.0, 1582.0, 1583.0, 1584.0, 1585.0, 1586.0, 1588.0, 1589.0, 1590.0, 1591.0, 1592.0, 1593.0, 1594.0, 1595.0, 1596.0, 1597.0, 1598.0, 1599.0, 1600.0, 1601.0, 1603.0, 1605.0, 1606.0, 1607.0, 1608.0, 8460.0, 1610.0, 1611.0, 1612.0, 1613.0, 1609.0, 1615.0, 1614.0, 1617.0, 1616.0, 16604.0, 1620.0, 1621.0, 1622.0, 1623.0, 1624.0, 1625.0, 1626.0, 1627.0, 1628.0, 1629.0, 1630.0, 1631.0, 1632.0, 9824.0, 1634.0, 1637.0, 1638.0, 1639.0, 1640.0, 1641.0, 1642.0, 1643.0, 1644.0, 1645.0, 1646.0, 1647.0, 1648.0, 1649.0, 1650.0, 1651.0, 1652.0, 1654.0, 1655.0, 1659.0, 1660.0, 1661.0, 1662.0, 1664.0, 1665.0, 1666.0, 1667.0, 1668.0, 1669.0, 1670.0, 1671.0, 1672.0, 1673.0, 1674.0, 1675.0, 1677.0, 1678.0, 1679.0, 1680.0, 1681.0, 1682.0, 1683.0, 1684.0, 1685.0, 9878.0, 1687.0, 9880.0, 1689.0, 34458.0, 1691.0, 1686.0, 1690.0, 1694.0, 1695.0, 1696.0, 1693.0, 1698.0, 1700.0, 1701.0, 1702.0, 1703.0, 1704.0, 1705.0, 1706.0, 1707.0, 1708.0, 1710.0, 1711.0, 1713.0, 1714.0, 1715.0, 1716.0, 9910.0, 1718.0, 1720.0, 1721.0, 1722.0, 1723.0, 1724.0, 1725.0, 8483.0, 1730.0, 1731.0, 1732.0, 1733.0, 9926.0, 9927.0, 1734.0, 1735.0, 91848.0, 1739.0, 1736.0, 1741.0, 1742.0, 1738.0, 1737.0, 1745.0, 1746.0, 1747.0, 1740.0, 1749.0, 1744.0, 1750.0, 1752.0, 1753.0, 1754.0, 1755.0, 18140.0, 1758.0, 9951.0, 1760.0, 1759.0, 1761.0, 1764.0, 1765.0, 9957.0, 1767.0, 1768.0, 1769.0, 1770.0, 352.0, 1774.0, 1777.0, 1778.0, 1780.0, 1781.0, 1782.0, 1783.0, 1784.0, 1785.0, 1786.0, 1787.0, 1788.0, 1789.0, 1793.0, 1795.0, 1796.0, 1797.0, 9990.0, 1799.0, 1798.0, 1801.0, 1802.0, 1803.0, 1804.0, 1806.0, 1808.0, 1809.0, 1810.0, 1811.0, 10004.0, 1813.0, 1814.0, 1816.0, 1818.0, 1819.0, 1821.0, 1822.0, 1823.0, 1825.0, 10019.0, 1828.0, 1829.0, 1830.0, 1831.0, 1832.0, 1834.0, 1835.0, 1836.0, 1838.0, 1839.0, 1840.0, 10032.0, 1841.0, 1843.0, 1844.0, 1845.0, 1846.0, 1847.0, 1848.0, 34617.0, 1849.0, 1851.0, 1853.0, 1854.0, 1855.0, 1857.0, 1858.0, 1859.0, 67396.0, 1860.0, 1861.0, 1863.0, 1864.0, 1865.0, 1866.0, 1869.0, 1870.0, 10063.0, 1872.0, 1873.0, 1871.0, 1875.0, 10068.0, 1876.0, 1878.0, 1879.0, 1880.0, 1881.0, 374.0, 10075.0, 1884.0, 1885.0, 1888.0, 1889.0, 1890.0, 1891.0, 1893.0, 1894.0, 1895.0, 1896.0, 18281.0, 1898.0, 1899.0, 1900.0, 1903.0, 1905.0, 1908.0, 1909.0, 1910.0, 1911.0, 1912.0, 1913.0, 1914.0, 10107.0, 1916.0, 1917.0, 1918.0, 1919.0, 1920.0, 1921.0, 1922.0, 1924.0, 1926.0, 1928.0, 1929.0, 1930.0, 1931.0, 1932.0, 1936.0, 1940.0, 1943.0, 1945.0, 1948.0, 1950.0, 1951.0, 1952.0, 1953.0, 1955.0, 1956.0, 1957.0, 1958.0, 1959.0, 1961.0, 1962.0, 1965.0, 1966.0, 1967.0, 1968.0, 1969.0, 1971.0, 1972.0, 1976.0, 1979.0, 1980.0, 10173.0, 1982.0, 1983.0, 1984.0, 1981.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1997.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2007.0, 399.0, 2008.0, 2011.0, 34780.0, 2012.0, 2014.0, 2013.0, 2016.0, 2018.0, 2020.0, 2021.0, 10214.0, 10215.0, 2024.0, 2025.0, 2026.0, 2027.0, 2028.0, 2029.0, 2030.0, 2031.0, 2032.0, 2033.0, 2034.0, 2035.0, 2036.0, 10228.0, 2038.0, 2037.0, 2040.0, 41111.0, 10234.0, 2041.0, 2044.0, 2043.0, 2046.0, 2048.0, 2049.0, 2050.0, 2051.0, 2052.0, 2053.0, 2055.0, 67592.0, 2056.0, 2058.0, 2059.0, 2060.0, 2061.0, 2063.0, 2064.0, 2065.0, 2066.0, 2067.0, 2071.0, 2072.0, 2073.0, 2075.0, 2076.0, 2077.0, 2078.0, 2079.0, 2080.0, 16696.0, 2083.0, 2084.0, 2086.0, 2088.0, 2089.0, 2090.0, 2092.0, 2095.0, 10288.0, 2097.0, 2096.0, 10291.0, 2100.0, 2101.0, 2103.0, 2104.0, 2105.0, 2106.0, 2109.0, 2110.0, 2111.0, 2116.0, 2119.0, 18504.0, 2122.0, 2125.0, 2126.0, 2127.0, 2128.0, 2129.0, 2131.0, 2133.0, 2134.0, 2136.0, 2137.0, 2140.0, 2141.0, 2142.0, 2143.0, 2144.0, 2146.0, 2147.0, 2148.0, 2149.0, 2150.0, 10342.0, 2152.0, 2153.0, 2154.0, 10344.0, 2156.0, 2158.0, 2159.0, 2160.0, 2161.0, 2162.0, 2163.0, 10355.0, 2165.0, 10357.0, 2167.0, 2170.0, 2171.0, 2172.0, 2174.0, 2176.0, 2178.0, 2179.0, 2180.0, 2182.0, 2184.0, 2185.0, 2186.0, 2187.0, 2188.0, 2189.0, 2190.0, 2193.0, 2194.0, 2195.0, 2196.0, 2197.0, 2198.0, 2199.0, 2204.0, 2205.0, 2206.0, 2208.0, 2209.0, 10402.0, 2210.0, 2211.0, 2213.0, 2214.0, 2215.0, 2212.0, 2218.0, 2219.0, 2220.0, 2223.0, 2225.0, 2228.0, 2229.0, 2230.0, 2231.0, 2232.0, 2234.0, 2236.0, 2237.0, 10430.0, 10431.0, 2240.0, 2238.0, 2241.0, 2243.0, 2239.0, 2245.0, 2244.0, 2247.0, 2248.0, 2249.0, 2250.0, 2251.0, 2252.0, 10445.0, 2253.0, 8230.0, 2256.0, 2257.0, 2258.0, 2259.0, 2260.0, 2261.0, 2262.0, 2263.0, 2255.0, 2265.0, 2267.0, 8592.0, 2270.0, 2273.0, 2274.0, 2276.0, 2278.0, 2279.0, 2282.0, 2283.0, 2284.0, 8595.0, 2286.0, 2287.0, 2288.0, 2289.0, 2291.0, 2292.0, 2293.0, 2294.0, 2296.0, 2297.0, 2298.0, 2299.0, 10226.0, 2301.0, 2302.0, 2303.0, 2304.0, 2305.0, 2306.0, 2307.0, 2308.0, 2309.0, 459.0, 10503.0, 2312.0, 2313.0, 8601.0, 2315.0, 2318.0, 8602.0, 2319.0, 2322.0, 2324.0, 10517.0, 2326.0, 2328.0, 10520.0, 2336.0, 2340.0, 2343.0, 2346.0, 2347.0, 2348.0, 8234.0, 2350.0, 2352.0, 2354.0, 2355.0, 2356.0, 2358.0, 2359.0, 43320.0, 2361.0, 2362.0, 18749.0, 2365.0, 2367.0, 471.0, 2371.0, 2374.0, 2375.0, 2377.0, 2378.0, 2380.0, 8614.0, 2381.0, 2383.0, 2382.0, 2385.0, 2387.0, 2388.0, 2389.0, 2390.0, 2391.0, 2392.0, 2393.0, 2395.0, 2396.0, 2397.0, 2400.0, 2403.0, 2405.0, 10598.0, 2407.0, 2408.0, 2406.0, 479.0, 2411.0, 2410.0, 2413.0, 2414.0, 2415.0, 2416.0, 2417.0, 2420.0, 2422.0, 2423.0, 2426.0, 2429.0, 2430.0, 2431.0, 8624.0, 2432.0, 2433.0, 2435.0, 2436.0, 2439.0, 2440.0, 2441.0, 2442.0, 2445.0, 2447.0, 2450.0, 2451.0, 2454.0, 2456.0, 2457.0, 2458.0, 2459.0, 2461.0, 2462.0, 2466.0, 2467.0, 2469.0, 2471.0, 2472.0, 2473.0, 2474.0, 2475.0, 2476.0, 2478.0, 2479.0, 2480.0, 2482.0, 2486.0, 2489.0, 2490.0, 2491.0, 2492.0, 495.0, 27071.0, 2496.0, 2497.0, 2495.0, 18883.0, 92612.0, 10693.0, 2502.0, 2503.0, 2504.0, 2505.0, 2506.0, 2507.0, 2508.0, 2509.0, 2510.0, 2511.0, 2512.0, 2513.0, 2514.0, 2517.0, 2518.0, 2519.0, 2520.0, 2521.0, 2522.0, 2525.0, 2526.0, 2527.0, 2528.0, 2529.0, 10721.0, 2531.0, 2534.0, 2536.0, 2537.0, 2539.0, 2542.0, 2545.0, 8647.0, 2548.0, 2549.0, 2550.0, 2551.0, 2558.0, 2560.0, 509.0, 2562.0, 2564.0, 2569.0, 2571.0, 10769.0, 2578.0, 2579.0, 2580.0, 2582.0, 2583.0, 2585.0, 2586.0, 2587.0, 2591.0, 2593.0, 2594.0, 2595.0, 2596.0, 10785.0, 2599.0, 2600.0, 517.0, 2603.0, 2605.0, 2606.0, 2608.0, 18993.0, 2609.0, 2611.0, 10802.0, 2613.0, 2612.0, 2616.0, 2618.0, 2619.0, 2620.0, 2621.0, 2627.0, 2628.0, 2629.0, 2631.0, 2632.0, 2633.0, 2634.0, 2636.0, 2638.0, 2639.0, 2640.0, 2641.0, 2642.0, 2643.0, 2646.0, 2648.0, 2650.0, 2653.0, 2654.0, 2657.0, 2659.0, 24952.0, 10853.0, 2661.0, 2663.0, 2664.0, 530.0, 2670.0, 2671.0, 2673.0, 2674.0, 2675.0, 10871.0, 2680.0, 10873.0, 2682.0, 2681.0, 10876.0, 2685.0, 2686.0, 2687.0, 10881.0, 2691.0, 2695.0, 27274.0, 2700.0, 2701.0, 2702.0, 2706.0, 2708.0, 19094.0, 2710.0, 2712.0, 2713.0, 2714.0, 2711.0, 2715.0, 2717.0, 2718.0, 2719.0, 2720.0, 2722.0, 2725.0, 2727.0, 2732.0, 2735.0, 2737.0, 2738.0, 2739.0, 2740.0, 2741.0, 2742.0, 2745.0, 2747.0, 2748.0, 2750.0, 2751.0, 2752.0, 2753.0, 2755.0, 2756.0, 2758.0, 2759.0, 2761.0, 2762.0, 549.0, 2764.0, 2765.0, 2767.0, 10961.0, 2770.0, 2772.0, 2774.0, 2776.0, 2778.0, 2783.0, 2785.0, 2787.0, 2789.0, 2791.0, 2792.0, 2794.0, 2797.0, 2799.0, 2800.0, 2804.0, 2806.0, 2808.0, 2809.0, 11002.0, 2811.0, 2812.0, 2814.0, 2816.0, 2819.0, 2821.0, 2822.0, 2823.0, 2825.0, 2826.0, 2827.0, 2828.0, 2829.0, 2833.0, 8704.0, 2835.0, 2836.0, 2837.0, 2842.0, 2845.0, 2846.0, 2851.0, 2852.0, 2853.0, 2855.0, 2857.0, 2861.0, 2863.0, 2864.0, 2865.0, 2866.0, 2867.0, 2870.0, 2871.0, 2872.0, 2873.0, 11062.0, 2876.0, 2878.0, 2880.0, 11074.0, 2883.0, 2882.0, 2885.0, 2887.0, 2889.0, 2890.0, 2891.0, 11083.0, 2892.0, 2897.0, 2901.0, 2904.0, 2905.0, 2907.0, 2910.0, 2911.0, 8720.0, 2914.0, 2916.0, 2917.0, 2918.0, 2923.0, 2928.0, 2930.0, 2931.0, 2935.0, 2939.0, 2941.0, 8726.0, 2944.0, 2943.0, 2947.0, 11149.0, 2958.0, 2959.0, 2960.0, 2961.0, 2962.0, 2963.0, 2964.0, 2966.0, 2967.0, 2969.0, 2974.0, 2977.0, 2979.0, 2980.0, 2982.0, 2983.0, 2984.0, 2985.0, 2987.0, 2988.0, 2993.0, 2996.0, 2997.0, 3002.0, 3003.0, 3004.0, 11197.0, 3005.0, 3007.0, 11200.0, 3008.0, 11206.0, 3015.0, 3016.0, 599.0, 3018.0, 3021.0, 3022.0, 3024.0, 3025.0, 3026.0, 3028.0, 3030.0, 3031.0, 3033.0, 3035.0, 3037.0, 3040.0, 3041.0, 3043.0, 3044.0, 27619.0, 3046.0, 3047.0, 3048.0, 3050.0, 3052.0, 3053.0, 3054.0, 3055.0, 3056.0, 3058.0, 3061.0, 3066.0, 3067.0, 3068.0, 3069.0, 3071.0, 3072.0, 3076.0, 3077.0, 11269.0, 3080.0, 3082.0, 3083.0, 3084.0, 35854.0, 3092.0, 3093.0, 3094.0, 8756.0, 3096.0, 3098.0, 3100.0, 3101.0, 3110.0, 3112.0, 3114.0, 3117.0, 3119.0, 3121.0, 3125.0, 3128.0, 3130.0, 3135.0, 3137.0, 624.0, 3142.0, 3146.0, 3147.0, 3150.0, 3151.0, 3153.0, 3154.0, 3156.0, 3157.0, 16910.0, 3159.0, 3161.0, 3162.0

#### 11. Adjust the data types in order to avoid future issues. Which ones should be changed?

In [43]:
users_posts.dtypes
users_posts['ViewCount'] = users_posts['ViewCount'].astype('int64')
users_posts['ViewCount'].dtype

dtype('int64')

#### Bonus: Identify extreme values in your merged dataframe as you have learned in class, create a dataframe called outliers with the same columns as our data set and calculate the bounds. The values of the outliers dataframe will be the values of the merged_df that fall outside that bounds. You will need to save your outliers dataframe to a csv file on your-code folder.

In [54]:
stats = users_posts.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']

outliers = pd.DataFrame(columns=users_posts.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = users_posts[(users_posts[col] < lower) | 
                   (users_posts[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)
outliers.head()

outliers = outliers.to_csv('/home/alejandro/IRONHACK/LABORATORIOS/datamad0119/module-1/lab-data_cleaning/your-code/outliers.csv', index=False)