In [135]:
import pandas as pd

data = pd.read_csv('GSAF5.csv')
data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [136]:
data = data.rename(index=str, columns={"Case Number": "Case_Number", "Sex ": "Sex", 
                                       "Fatal (Y/N)": "Fatal_Y/N", "Species ": "Species",
                                       "Investigator or Source": "Investigator_or_Source", 
                                       "href formula": "href_formula", "Case Number.1": "Case_Number_1", 
                                       "Case Number.2": "Case_Number_2",
                                       "original order": "original_order", "Unnamed: 22": "Unnamed:_22", 
                                       "Unnamed: 23": "Unnamed:_23"})
data.head()

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_or_Source,pdf,href_formula,href,Case_Number_1,Case_Number_2,original_order,Unnamed:_22,Unnamed:_23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [ ]:
null_cols = data.isnull().sum()
null_cols[null_cols > 0]

In [137]:
data_href = data.where(data['href_formula'] == data['href'])
data_href.head()

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_or_Source,pdf,href_formula,href,Case_Number_1,Case_Number_2,original_order,Unnamed:_22,Unnamed:_23
0,2016.09.18.c,18-Sep-16,2016.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993.0,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992.0,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991.0,NaN,NaN
3,2016.09.17,17-Sep-16,2016.0,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990.0,NaN,NaN
4,2016.09.15,16-Sep-16,2016.0,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989.0,NaN,NaN

In [128]:
data_href = data[['href_formula', 'href']]


in_href_formula_not_in_href = list(set(data_href['href_formula'])-(set(data_href['href'])))
in_href_not_in_href_formula = list(set(data_href['href'])-(set(data_href['href_formula'])))

print(len(in_href_formula_not_in_href))
print(len(in_href_not_in_href_formula))

53
45

In [129]:
data_Case_Number_1 = data[['Case_Number', 'Case_Number_1']]


in_Case_Number_not_in_Case_Number_1 = list(set(data_Case_Number_1['Case_Number'])-(set(data_Case_Number_1['Case_Number_1'])))
in_Case_Number_1_not_in_Case_Number = list(set(data_Case_Number_1['Case_Number_1'])-(set(data_Case_Number_1['Case_Number'])))

print(len(in_Case_Number_not_in_Case_Number_1))
print(len(in_Case_Number_1_not_in_Case_Number))

data_Case_Number_2 = data[['Case_Number', 'Case_Number_2']]


in_Case_Number_not_in_Case_Number_2 = list(set(data_Case_Number_2['Case_Number'])-(set(data_Case_Number_2['Case_Number_2'])))
in_Case_Number_2_not_in_Case_Number = list(set(data_Case_Number_2['Case_Number_2'])-(set(data_Case_Number_2['Case_Number'])))

print(len(in_Case_Number_not_in_Case_Number_2))
print(len(in_Case_Number_not_in_Case_Number_2))

13
12
2
2

In [130]:
data = data.drop(columns=['href', 'Case_Number_1', 'Case_Number_2', 'Unnamed:_22', 'Unnamed:_23'])
data.head(2)

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal_Y/N,Time,Species,Investigator_or_Source,pdf,href_formula,original_order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5992

In [132]:
print(set(data['Country']))

{nan, 'MEDITERRANEAN SEA', 'WESTERN SAMOA', ' PHILIPPINES', 'VANUATU', 'NORTH ATLANTIC OCEAN ', 'MALAYSIA', 'ARGENTINA', 'CUBA', 'IRELAND', 'SUDAN?', 'NETHERLANDS ANTILLES', 'TAIWAN', 'PALESTINIAN TERRITORIES', 'MOZAMBIQUE', 'SRI LANKA', 'SOLOMON ISLANDS / VANUATU', 'FALKLAND ISLANDS', 'FRENCH POLYNESIA', 'GREECE', 'GRENADA', 'MEDITERRANEAN SEA?', 'INDONESIA', 'NICARAGUA ', 'St Helena', 'MAYOTTE', 'SLOVENIA', 'CAYMAN ISLANDS', 'JOHNSTON ISLAND', 'BRITISH VIRGIN ISLANDS', 'LIBYA', 'FIJI', 'RED SEA / INDIAN OCEAN', 'BRITISH ISLES', 'ATLANTIC OCEAN', 'Between PORTUGAL & INDIA', 'CYPRUS', 'PANAMA', 'ANTIGUA', 'TURKEY', 'KENYA', 'SOUTHWEST PACIFIC OCEAN', 'TUNISIA', 'PHILIPPINES', 'AUSTRALIA', 'SOLOMON ISLANDS', 'TUVALU', 'Seychelles', 'ICELAND', 'MEXICO', 'PUERTO RICO', 'ANDAMAN / NICOBAR ISLANDAS', 'BAY OF BENGAL', 'SCOTLAND', 'JAMAICA', 'NEW CALEDONIA', 'MONACO', 'SUDAN', 'YEMEN ', 'TONGA', 'TURKS & CAICOS', 'CANADA', 'DOMINICAN REPUBLIC', 'TANZANIA', 'NICARAGUA', 'MADAGASCAR', 'BAHAMAS', 'VENEZUELA', 'PALAU', 'SIERRA LEONE', 'HAITI', 'GUINEA', 'MAURITIUS', 'GHANA', 'BAHREIN', 'ST. MARTIN', 'BURMA', 'ADMIRALTY ISLANDS', 'PARAGUAY', 'SYRIA', 'TRINIDAD & TOBAGO', 'KUWAIT', 'CROATIA', 'YEMEN', 'GULF OF ADEN', 'ARUBA', 'JAPAN', 'CAPE VERDE', 'DIEGO GARCIA', 'SAMOA', 'EL SALVADOR', 'PORTUGAL', 'NEW GUINEA', 'MID ATLANTIC OCEAN', 'LEBANON', 'MALDIVE ISLANDS', 'Sierra Leone', 'MARSHALL ISLANDS', 'NEW ZEALAND', 'SAUDI ARABIA', 'ASIA?', 'GRAND CAYMAN', 'SPAIN', 'NORWAY', 'NORTHERN ARABIAN SEA', 'MEXICO ', 'CENTRAL PACIFIC', 'MID-PACIFC OCEAN', 'ITALY / CROATIA', 'INDIAN OCEAN', 'RED SEA', 'AZORES', 'AMERICAN SAMOA', 'CHILE', 'KIRIBATI', 'RUSSIA', 'SOMALIA', 'IRAN', 'SOUTH ATLANTIC OCEAN', 'USA', 'GABON', 'FRANCE', 'IRAQ', 'HONG KONG', 'BRITISH NEW GUINEA', 'THAILAND', 'DJIBOUTI', 'COSTA RICA', 'SOUTH CHINA SEA', 'EGYPT / ISRAEL', 'UNITED KINGDOM', 'NEW BRITAIN', 'ISRAEL', 'MICRONESIA', 'MARTINIQUE', 'INDIA', 'COLUMBIA', 'BERMUDA', 'UNITED ARAB EMIRATES (UAE)', 'OCEAN', 'CARIBBEAN SEA', 'SAN DOMINGO', 'ITALY', 'SOUTH AFRICA', 'PACIFIC OCEAN ', 'MALTA', 'SENEGAL', 'ECUADOR', 'EQUATORIAL GUINEA / CAMEROON', 'Coast of AFRICA', 'SWEDEN', 'EGYPT ', 'FEDERATED STATES OF MICRONESIA', 'NEVIS', 'NORTH ATLANTIC OCEAN', 'ANGOLA', 'VIETNAM', 'NORTHERN MARIANA ISLANDS', 'GUATEMALA', 'SEYCHELLES', 'UNITED ARAB EMIRATES', 'TASMAN SEA', 'BARBADOS', 'CHINA', 'PERSIAN GULF', 'JAVA', 'BELIZE', 'BRAZIL', 'GREENLAND', 'GEORGIA', 'CURACAO', 'URUGUAY', 'GUYANA', 'BANGLADESH', ' TONGA', 'NORTH PACIFIC OCEAN', 'SOUTH PACIFIC OCEAN', 'MONTENEGRO', 'LIBERIA', 'INDIAN OCEAN?', 'COOK ISLANDS', 'KOREA', 'OKINAWA', 'NORTH SEA', 'REUNION', 'ALGERIA', 'NIGERIA', 'GUAM', 'CRETE', 'NAMIBIA', 'IRAN / IRAQ', 'CEYLON (SRI LANKA)', 'HONDURAS', 'RED SEA?', 'PAPUA NEW GUINEA', 'THE BALKANS', 'EGYPT', 'ST. MAARTIN', 'SOUTH KOREA', 'ENGLAND', 'BRITISH WEST INDIES', 'SINGAPORE', 'PACIFIC OCEAN', 'Fiji'}

In [ ]:
data[['displ', 'cylinders']] = data[['displ', 'cylinders']].fillna(0)



data.loc[(data['cylinders']==0) & (data['displ']!=0), 'cylinders'] = 4



df_without_nulls['trany'] = df_without_nulls['trany'].str.replace('-', '')
df_without_nulls['trany'] = df_without_nulls['trany'].str.replace('Automatic', 'Auto')
df_without_nulls['trany'] = df_without_nulls['trany'].str.replace('Auto\(', 'Auto ')
df_without_nulls['trany'] = df_without_nulls['trany'].str.replace('Manual\(', 'Manual ')
df_without_nulls['trany'] = df_without_nulls['trany'].str.replace('\(', '')
df_without_nulls['trany'] = df_without_nulls['trany'].str.replace('\)', '')
print(set(df_without_nulls['trany']))



before = len(df_without_nulls)
df_without_nulls = df_without_nulls.drop_duplicates()
after = len(df_without_nulls)
print('Number of duplicate records dropped: ', str(before - after))



data['year'] = data['year'].astype('object')
data['year'].dtype