In [28]:
import requests
from bs4 import BeautifulSoup

In [30]:

def getNoticia(url):
    html = requests.get(url).content
    soup = BeautifulSoup(html, "lxml")                                           
    noticia = {
        "titular": soup.find_all('h1')[0].text,
        "texto": ' '.join(map(lambda t: t.text if len(t.attrs) == 0 else '' , soup.find_all('p'))).strip()
    } 
    return noticia

display(getNoticia('https://www.reuters.com/article/us-shazam-m-a-apple-eu/eu-clears-apples-purchase-of-shazam-idUSKCN1LM1TZ'))
display(getNoticia('https://www.reuters.com/article/us-britain-labour-technology/well-take-on-social-media-giants-uks-opposition-labour-party-says-idUSKCN1PV0PL'))

{'titular': "EU clears Apple's purchase of Shazam",
 'texto': 'BRUSSELS (Reuters) - The European Union approved Apple’s planned acquisition of British music discovery app Shazam on Thursday, saying an EU antitrust investigation showed it would not harm competition in the bloc.  The deal, announced in December last year, would help the iPhone maker better compete with Spotify, the industry leader in music streaming services. Shazam identifies songs when a smartphone is pointed at an audio source.  “After thoroughly analyzing Shazam’s user and music data, we found that their acquisition by Apple would not reduce competition in the digital music streaming market,” EU competition commissioner Margrethe Vestager said in a statement.  “Data is key in the digital economy. We must therefore carefully review transactions which lead to the acquisition of important sets of data, including potentially commercially sensitive ones,” she added.  The European Commission opened a full-scale investigation into the deal in April, emblematic of its recent worries that companies may buy a data-rich rival to mine it for information or drive others out of the market.  Reuters last month reported sources saying that Apple was set to win unconditional EU antitrust approval for the deal following the probe requested by seven European countries including France, Italy, Spain and Sweden.   All quotes delayed a minimum of 15 minutes. See here for a complete list of exchanges and delays. © 2019 Reuters. All Rights Reserved.'}

{'titular': "We'll take on social media giants, UK's opposition Labour Party says",
 'texto': 'LONDON (Reuters) - Digital tech firms are too big and Britain’s opposition Labour Party would create a dedicated technology regulator to prevent market abuse and look at breaking up monopolies like Facebook, the party’s deputy leader will say on Wednesday.  The digital revolution has spawned a handful of U.S.-based technology companies since the 1990s that now have a combined financial and cultural power greater than most sovereign states.  Tom Watson will lay out plans which include creating a regulator, creating a Digital Bill of Rights and giving social media firms a broad legal duty of care to protect users.  “The scale of the largest companies is rightly the subject of scrutiny. We should take seriously the calls to break them up if it is in the public interest,” Watson is expected to say.  Facebook in particular has come under scrutiny over its use of data. Concerns about its ability to safeguard user data have sparked a government lawsuit in the United States, while it has been criticized by lawmakers around the world.  Shares have been hit by investors concern about snowballing legal and regulatory efforts over its data use polices.  Labour did not set out in detail how a British regulator might attempt to break up some of the most powerful companies in the world, almost of which are based outside the United Kingdom.  In a interview with BBC radio, Watson cited Facebook’s purchase of Instagram an example of a merger that concentrated user data in a dangerous way.  “Our competition laws are not fit for the age of big data,” he said.   All quotes delayed a minimum of 15 minutes. See here for a complete list of exchanges and delays. © 2019 Reuters. All Rights Reserved.'}

In [32]:
url = 'https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy'
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")

In [38]:
table = soup.find_all('table',{'class':'sortable wikitable'})[0]
rows = table.find_all('tr')
rows = [row.text.strip().split("\n") for row in rows]
rows

[['Country', 'Life expectancy'],
 ['Albania', '78'],
 ['Austria', '82'],
 ['Belarus', '74'],
 ['Belgium', '81'],
 ['Bosnia and Herzegovina', '77'],
 ['Bulgaria', '75'],
 ['Croatia', '77'],
 ['Cyprus', '80'],
 ['Czech Republic', '79'],
 ['Denmark', '81'],
 ['Estonia', '77'],
 ['Finland', '81'],
 ['France', '83'],
 ['Germany', '81'],
 ['Greece', '81'],
 ['Hungary', '76'],
 ['Iceland', '83'],
 ['Ireland', '82'],
 ['Italy', '83'],
 ['Kazakhstan', '72'],
 ['Latvia', '74'],
 ['Liechtenstein', '82'],
 ['Lithuania', '75'],
 ['Luxembourg', '82'],
 ['Macedonia', '76'],
 ['Malta', '82'],
 ['Republic of Moldova', '71'],
 ['Montenegro', '77'],
 ['Netherlands', '82'],
 ['Norway', '82'],
 ['Poland', '78'],
 ['Portugal', '82'],
 ['Romania', '75'],
 ['Russian Federation', '71'],
 ['Serbia', '75'],
 ['Slovakia', '77'],
 ['Slovenia', '81'],
 ['Spain', '83'],
 ['Sweden', '83'],
 ['Switzerland', '83'],
 ['Turkey', '75'],
 ['Ukraine', '71'],
 ['United Kingdom', '82']]

In [58]:
import pandas as pd 
df = pd.DataFrame(rows[1:],columns=rows[0])

In [82]:
df = df.sort_values(ascending=False, by="Life expectancy")
df = df.reset_index(drop=True)
df["Life expectancy"] = df["Life expectancy"].astype(int)
df

                   Country  Life expectancy
0                  Iceland               83
1              Switzerland               83
2                   Sweden               83
3                    Spain               83
4                    Italy               83
5                   France               83
6            Liechtenstein               82
7                 Portugal               82
8                   Norway               82
9              Netherlands               82
10                   Malta               82
11              Luxembourg               82
12                 Austria               82
13                 Ireland               82
14          United Kingdom               82
15                 Germany               81
16                 Finland               81
17                 Belgium               81
18                Slovenia               81
19                 Denmark               81
20                  Greece               81
21                  Cyprus               80
22          Czech Republic               79
23                 Albania               78
24                  Poland               78
25  Bosnia and Herzegovina               77
26                Slovakia               77
27                 Croatia               77
28              Montenegro               77
29                 Estonia               77
30               Macedonia               76
31                 Hungary               76
32                  Serbia               75
33                 Romania               75
34               Lithuania               75
35                Bulgaria               75
36                  Turkey               75
37                  Latvia               74
38                 Belarus               74
39              Kazakhstan               72
40     Republic of Moldova               71
41      Russian Federation               71
42                 Ukraine               71

In [84]:
df["¿Mola?"] = pd.cut(df["Life expectancy"], bins=[df["Life expectancy"].min()-1,80,df["Life expectancy"].max()+1], labels=["Nomola","Mola"])

In [88]:
df.groupby("¿Mola?").agg({"Life expectancy":"mean"})

        Life expectancy
¿Mola?
Nomola        75.454545
Mola          82.000000