# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [3]:
lst = [i for i in range(1, 51)]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [5]:
lst = [i for i in range(2, 201) if i %2 == 0]
print(lst)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [10]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [11]:
lst = [y for x in a for y in x]
print(lst)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [119]:
lst = [y for x in a for y in x if y >= 0.5]
print(lst)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [131]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [132]:
lst = [z for x in b for y in x for z in y]
print(lst)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [134]:
lst1 = [y for x in b for y in x if y[2] <= 0.5]
print(lst1)

[array([0.55867166, 0.06210792, 0.08147297]), array([0.82579068, 0.91512478, 0.06833034]), array([0.05440634, 0.65857693, 0.30296619]), array([0.09143215, 0.71893382, 0.45850679]), array([0.71600294, 0.87392666, 0.11434044]), array([0.8694668 , 0.65669313, 0.10708681]), array([0.07529684, 0.46470767, 0.47984544]), array([0.65368638, 0.14901286, 0.23760688])]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [32]:
import os
import pandas as pd

file_list = [f for f in os.listdir('/home/alejandro/IRONHACK/LABORATORIOS/datamad0119/module-1/lab-list-comprehensions/data') if f.endswith('.csv')]

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [40]:
data_sets = [pd.read_csv(os.path.join('/home/alejandro/IRONHACK/LABORATORIOS/datamad0119/module-1/lab-list-comprehensions/data', f)) for f in file_list]
data = pd.concat(data_sets, axis=0)
data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.215190,0.155352,0.160848,0.807736,0.363587,0.899832,0.146754,0.094802,0.705133,0.882762,0.773320,0.687745,0.016789,0.340725,0.984182,0.985461,0.412044,0.867894,0.113432,0.349845
1,0.895544,0.955196,0.089925,0.827555,0.089071,0.642883,0.996052,0.879020,0.421837,0.412141,0.858513,0.217091,0.176157,0.551236,0.834378,0.419535,0.041431,0.602258,0.984628,0.516899
2,0.413752,0.693052,0.789796,0.929164,0.536191,0.439769,0.773474,0.982074,0.876955,0.633154,0.279005,0.483317,0.908288,0.756172,0.462130,0.289892,0.145233,0.076819,0.797836,0.197592
3,0.728001,0.348156,0.935787,0.851163,0.444573,0.715080,0.988408,0.210332,0.732133,0.892383,0.216893,0.367595,0.846208,0.240111,0.471880,0.399721,0.758196,0.665568,0.931542,0.448124
4,0.134942,0.875931,0.273505,0.207588,0.080696,0.717396,0.033930,0.646837,0.888722,0.922742,0.176593,0.861333,0.389451,0.695244,0.129955,0.364114,0.428224,0.365442,0.847818,0.588319
0,0.702566,0.092336,0.245083,0.918402,0.695110,0.886921,0.588605,0.950970,0.168079,0.783107,0.698836,0.120857,0.207432,0.824789,0.349212,0.818606,0.376941,0.886644,0.472826,0.551858
1,0.177005,0.649551,0.467321,0.449597,0.458872,0.815586,0.455132,0.729812,0.998528,0.048724,0.377391,0.729498,0.721515,0.566724,0.338366,0.877239,0.129824,0.773155,0.485385,0.686294
2,0.689556,0.445586,0.005691,0.150171,0.554146,0.492320,0.185612,0.060855,0.457443,0.847337,0.603072,0.346574,0.898464,0.482963,0.443979,0.430132,0.713078,0.302786,0.051382,0.203699
3,0.047188,0.854596,0.833368,0.043878,0.883505,0.786302,0.980916,0.004030,0.619601,0.547769,0.160962,0.545281,0.931623,0.991855,0.821099,0.654592,0.346710,0.183948,0.372739,0.739383
4,0.936065,0.725831,0.184239,0.677391,0.242726,0.125457,0.356254,0.937350,0.215774,0.212762,0.483018,0.573162,0.634487,0.423924,0.394633,0.766967,0.606719,0.538712,0.885516,0.667051

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [87]:
selected_columns = [col for col in data._get_numeric_data() if data[col].median() < 0.48]
print(selected_columns)

['2', '9', '12', '14', '17', '20']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [85]:
data['20'] = data['19'] - 0.1
data.head(10)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.215190,0.155352,0.160848,0.807736,0.363587,0.899832,0.146754,0.094802,0.705133,0.882762,...,0.687745,0.016789,0.340725,0.984182,0.985461,0.412044,0.867894,0.113432,0.349845,0.249845
1,0.895544,0.955196,0.089925,0.827555,0.089071,0.642883,0.996052,0.879020,0.421837,0.412141,...,0.217091,0.176157,0.551236,0.834378,0.419535,0.041431,0.602258,0.984628,0.516899,0.416899
2,0.413752,0.693052,0.789796,0.929164,0.536191,0.439769,0.773474,0.982074,0.876955,0.633154,...,0.483317,0.908288,0.756172,0.462130,0.289892,0.145233,0.076819,0.797836,0.197592,0.097592
3,0.728001,0.348156,0.935787,0.851163,0.444573,0.715080,0.988408,0.210332,0.732133,0.892383,...,0.367595,0.846208,0.240111,0.471880,0.399721,0.758196,0.665568,0.931542,0.448124,0.348124
4,0.134942,0.875931,0.273505,0.207588,0.080696,0.717396,0.033930,0.646837,0.888722,0.922742,...,0.861333,0.389451,0.695244,0.129955,0.364114,0.428224,0.365442,0.847818,0.588319,0.488319
0,0.702566,0.092336,0.245083,0.918402,0.695110,0.886921,0.588605,0.950970,0.168079,0.783107,...,0.120857,0.207432,0.824789,0.349212,0.818606,0.376941,0.886644,0.472826,0.551858,0.451858
1,0.177005,0.649551,0.467321,0.449597,0.458872,0.815586,0.455132,0.729812,0.998528,0.048724,...,0.729498,0.721515,0.566724,0.338366,0.877239,0.129824,0.773155,0.485385,0.686294,0.586294
2,0.689556,0.445586,0.005691,0.150171,0.554146,0.492320,0.185612,0.060855,0.457443,0.847337,...,0.346574,0.898464,0.482963,0.443979,0.430132,0.713078,0.302786,0.051382,0.203699,0.103699
3,0.047188,0.854596,0.833368,0.043878,0.883505,0.786302,0.980916,0.004030,0.619601,0.547769,...,0.545281,0.931623,0.991855,0.821099,0.654592,0.346710,0.183948,0.372739,0.739383,0.639383
4,0.936065,0.725831,0.184239,0.677391,0.242726,0.125457,0.356254,0.937350,0.215774,0.212762,...,0.573162,0.634487,0.423924,0.394633,0.766967,0.606719,0.538712,0.885516,0.667051,0.567051

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [111]:
lst2 = [y for x in data for y in data[x] if y > 0.7 and y < 0.75]
print(lst2)

[0.7280006345208285, 0.7025657075988269, 0.7132714209987683, 0.7347510852128797, 0.7258310816144985, 0.736029494090402, 0.7472962776291713, 0.7358941798147411, 0.7365416322783028, 0.7088042362916818, 0.7343092314001137, 0.7023481768180954, 0.7329024831531535, 0.7133695725698419, 0.7476323136755818, 0.7008930873050235, 0.7150799992177622, 0.7173964318670598, 0.7032248108904495, 0.7013619954419494, 0.7357618655811269, 0.7268545088531969, 0.7124169515124726, 0.71223975981198, 0.7306642125209889, 0.7383982036983279, 0.7298115760258881, 0.7051334608870933, 0.7321333453970806, 0.7178166705957928, 0.7374449181749492, 0.7159290265157912, 0.7294980584878026, 0.7215147068185102, 0.7045750112959754, 0.7111584953876777, 0.7209375615129192, 0.7133690799930356, 0.7396561066717461, 0.7303553716733908, 0.7078738356977186, 0.7321533684342264, 0.7356923324968598, 0.7390312927111312, 0.7130781095091867, 0.7085098152301276, 0.7490680818183477, 0.7196096371031628, 0.7264121114538001, 0.7393833032570581, 0.7244863338885654, 0.7376946446827494, 0.7033930409580709, 0.7274869207330491]